# Generated by Django 6.0.6 on 2026-06-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('tech', 'Công nghệ'), ('fiction', 'Văn học'), ('selfhelp', 'Tự phát triển'), ('business', 'Kinh doanh')], default='tech', max_length=20),
        ),
    ]
