# Generated by Django 6.0.6 on 2026-06-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_book_price_order_orderitem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
    ]
