# Generated by Django 6.0.6 on 2026-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_truyen', models.CharField(max_length=200)),
                ('tac_gia', models.CharField(max_length=100)),
                ('anh_bia', models.ImageField(blank=True, null=True, upload_to='bia_truyen/')),
                ('the_loai', models.CharField(blank=True, max_length=100, null=True)),
                ('so_luong', models.IntegerField(default=1)),
                ('tom_tat', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
